# Generated by Django 6.0.2 on 2026-02-12 09:11

import blogapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[blogapp.validators.validate_file_size])),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[blogapp.validators.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[blogapp.validators.validate_file_size]),
        ),
    ]
